### ISSUE TITLE
Fix row/column mix-up in Maze2D

### ISSUE THREAD

**Issue by brendon-boldt** [citiususc/hipster#181] opened 2017-06-16 10:26 UTC
Class: `es.usc.citius.hipster.util.examples.maze.Maze2D`

In the nested for loop condition, `row` was used twice instead of `row` then `column` (line 124). This causes an a runtime error when trying to construct a `Maze2D` object with a `char[][]`.

**Comment by brendon-boldt** [comment] 2017-06-16 10:28
Currently making the pull request

**Comment by gonzalezsieira** [comment] 2017-06-16 10:41
Hi @brendon-boldt . This is a duplicate of #179, which was fixed in c33b47d74f8fe522ebd3ca75f1436bb60765ed93. Thank you for contributing to Hipster.

**Closed as completed by gonzalezsieira** 2017-06-16 10:41 UTC
